#ifndef __ISIS_CMD_CODES__
#define __ISIS_CMD_CODES__

#define ISIS_CONFIG_NODE_ENABLE 1
#define CMDCODE_SHOW_NODE_ISIS_PROTOCOL 2
#define CMDCODE_CONF_NODE_ISIS_PROTOCOL_INTF_ALL 3
#define CMDCODE_CONF_NODE_ISIS_PROTOCOL_INTF 4
#define CMDCODE_SHOW_NODE_ISIS_PROTOCOL_INTF_STATS 5
#define CMDCODE_CLEAR_NODE_ISIS_PROTOCOL 6
#define CMDCODE_CLEAR_NODE_ISIS_PROTOCOL_ADJACENCIES 7
#define CMDCODE_CONF_NODE_ISIS_PROTOCOL_INTF_HELLO_INTERVAL 8
#define CMDCODE_CONF_NODE_ISIS_PROTOCOL_INTF_HELLO_INTERVAL_PARAM 9
#define CMDCODE_CONF_NODE_ISIS_PROTOCOL_INTF_AUTH_CMD 10
#define CMDCODE_CONF_NODE_ISIS_PROTOCOL_INTF_AUTH_PARAM 11
#define CMDCODE_SHOW_NODE_ISIS_PROTOCOL_SINGLE_INTF_STATS 12
#define CMDCODE_SHOW_NODE_ISIS_PROTOCOL_L2MAP             13
#define CMDCODE_CONF_NODE_ISIS_PROTOCOL_INTF_CMD          14
#endif